Reijin71/web 159 close the upload portal on october 1st 2024
vinhloc30796/creativecontact-app pull request #104
Opened 2024-11-13 02:58 UTC by codingandcoffeerighthand

## Description

Close upload portal for ended event

## Key Changes

1. Add column to events table and add migration
2. Add caution ui for  ended event
3. Implement i18next for ended event page

## Breaking Changes

- Update database

## Related Issues

-  WEB-159

2024-11-15 07:18 UTC, vinhloc30796 commented on supabase/seed.sql
chạy `supabase db push` để chạy migration trên production trước khi merge PR nhé @codingandcoffeerighthand

2024-11-15 07:19 UTC, vinhloc30796 commented on supabase/seed.sql
với lại nhớ thêm cái time end cho Trung Thu Creative Archive trên production nữa nha @codingandcoffeerighthand

2024-11-15 07:25 UTC, vinhloc30796 requested changes
có hai chỗ quan trọng cần fix là (1) drizzle schema bỏ notNull và (2) conditional display cho EventEnded nên bỏ vào chỗ khác để đúng mục đích hơn nha @codingandcoffeerighthand

2024-11-15 07:25 UTC, vinhloc30796 commented on drizzle/schema/event.ts
> +  time_end: timestamp("time_end", { withTimezone: true }).notNull(),
@codingandcoffeerighthand time_end là nullable nha -- xóa `notNull()` em ơi

2024-11-15 07:25 UTC, vinhloc30796 commented on app/(public)/[eventSlug]/page.tsx
chỗ này không ổn lắm; mục tiêu là mọi người vẫn vào xem tranh ở `APP_URL/event/trungthu-archive-2024` nha, chỉ là không upload được nữa thôi. nếu e bỏ cái conditional chỗ này, thì là không vào xem tranh được luôn.

fix hộ anh nhé

2024-11-15 08:13 UTC, codingandcoffeerighthand commented on supabase/seed.sql
ok anh, em thêm time_end  Trung Thu Creative Archive ở seed, 
giờ update time_end  Trung Thu Creative Archive ở file migrate

2024-11-18 12:00 UTC, loc-tread-labs approved these changes
lgtm

2024-11-19 03:25 UTC, vinhloc30796 approved these changes
Lgtm

2024-11-19 03:25 UTC, merged