feat(portfolio): change the layout in Portfolio Edit page and make media vertically scrollable
vinhloc30796/creativecontact-app pull request #113
Opened 2024-11-21 12:35 UTC by notHisu

## Description

This PR changes the layout in `/portfolio/{artworkId}` according to Figma and make media vertically scrollable in `Profile Portfolio` tab & `Portfolio Edit` page

## Key Changes

1. Make media vertically scrollable `Profile Portfolio` tab & `Portfolio Edit` page
2. Create a new store `usePendingSizeStore`
3. Separate `DataUsage` to a new component

## Breaking Changes

None

## Related Issues

- Addresses WEB-224
- Addresses WEB-225

## Testing Instructions

None

## Additional Notes

None

2024-11-22 03:53 UTC, vinhloc30796 requested changes
@notHisu ơi làm thêm hộ anh ba cái nhé

- [x] chỉnh lại cái height của cái Profile Card cho nó gọn lại nha -- hiện nó đang bị dài loằng ngoằng á
- [x] chỉnh cái portfolio tab cho nó scroll riêng một mình nó thôi -- hiện giờ là scroll cả trang, mình muốn nếu portfolio tab dài quá, thì khi user scroll xuống xem ảnh, user vẫn xem được Profile Card (frozen in place ở cạnh) 
- [x] chỉnh lại cái media array cho nó không bị có một cái scroll riêng của nó nữa -- tại vì mình đã cho phép scroll cái portfolio tab rồi

2024-11-23 03:39 UTC, loc-tread-labs commented
Vẫn còn xíu nữa, nhưng thôi không sao, tạm ổn nha, để a fix nốt

Uploading Screen Recording 2024-11-23 103754.mp4…

2024-11-23 03:42 UTC, vinhloc30796 commented
vẫn còn xíu nữa layout, nhưng thôi k sao, để a fix nốt

2024-11-23 03:54 UTC, vinhloc30796 approved these changes
Layout cũm ổn á, còn xíu nữa em xem vid nha -- nhưng mà tại a thử edit mà save vẫn chưa được, cancel vẫn chưa được á, nên a tạo task mới nha https://linear.app/creative-contact/issue/WEB-225/fix-the-portfolio-edit-page-so-that-its-closer-to-figma

2024-11-23 03:58 UTC, merged